"""dedupe sent_menus by post_id instead of post_date

Revision ID: 40d5c3e37386
Revises: b960e6c756cf
Create Date: 2026-08-04 17:31:13.143692

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "40d5c3e37386"
down_revision: Union[str, Sequence[str], None] = "b960e6c756cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_subscription_post_date"), "sent_menus", type_="unique")
    op.create_unique_constraint(
        "uq_subscription_post_id", "sent_menus", ["subscription_id", "post_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_subscription_post_id", "sent_menus", type_="unique")
    op.create_unique_constraint(
        op.f("uq_subscription_post_date"),
        "sent_menus",
        ["subscription_id", "post_date"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
