"""add send_images to subscriptions

Revision ID: b960e6c756cf
Revises: f91efdc1c37c
Create Date: 2026-07-19 20:03:15.037553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b960e6c756cf'
down_revision: Union[str, Sequence[str], None] = 'f91efdc1c37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'subscriptions',
        sa.Column('send_images', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'send_images')
    # ### end Alembic commands ###
