"""change sent_menus image_url to image_urls array

Revision ID: d8e566dea3c3
Revises: 80f7d881e17b
Create Date: 2026-07-13 01:14:38.201008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8e566dea3c3'
down_revision: Union[str, Sequence[str], None] = '80f7d881e17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_menus', sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('sent_menus', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_menus', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sent_menus', 'image_urls')
    # ### end Alembic commands ###
