"""add platform column and rename facebook_page_name to source_handle

Revision ID: e55d0ce06ed6
Revises: d8e566dea3c3
Create Date: 2026-07-14 22:08:23.727435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e55d0ce06ed6"
down_revision: Union[str, Sequence[str], None] = "d8e566dea3c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("platform", sa.String(), nullable=False))
    op.add_column(
        "subscriptions", sa.Column("source_handle", sa.String(), nullable=False)
    )
    op.drop_column("subscriptions", "facebook_page_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "facebook_page_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("subscriptions", "source_handle")
    op.drop_column("subscriptions", "platform")
    # ### end Alembic commands ###
