"""add text_filter to subscriptions

Revision ID: f91efdc1c37c
Revises: e55d0ce06ed6
Create Date: 2026-07-19 13:49:30.377207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f91efdc1c37c"
down_revision: Union[str, Sequence[str], None] = "e55d0ce06ed6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("text_filter", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "text_filter")
    # ### end Alembic commands ###
